### ISSUE TITLE
Establishing a branch naming convention for Verigreen

### ISSUE THREAD

**Issue by rqc** [Verigreen/verigreen#11]
Hi,

I would suggest that we come up with a best practice for naming convention for the branches we create from `Verigreen` forks. I would suggest using an sticking to the following prefixes:
- `bug/<name>`: This is a bug that has been reported and it is being worked on.
- `feature/<name>`: This is an enhancement to the current code-base.
- `hotfix/<name>`: A fix that comes after a release is done for instance. 

I think we should eventually stop using the story numbers from our Agile Manager. I would suggest instead using the **issues** function in Github to open issues associated with our stories/tasks (e.g. we could have a reference to the story in the github issue description).

Any thoughts?

Ricardo

**Comment by eitansch** [comment]
+1
As for AgM - as I've stated offline, we're planning on syncing them together so regardless of where you work on them, the other side would be updated as well.

**Comment by soninob** [comment]
We should definitely ditch the AGM numbers until we can sync between them. 
Regarding the names, branches are not supposed to be kept in the system after merges.
The Q is how do we want it to look like after a merge in the commits history.
Another point is that I'm not sure that we can control it (assuming we are getting PRs from the outside world). A user is choosing as he understand best how to named the branch.
Last point, we can agree that every time that we will confirm a merge, then we can edit the commit message to our like.

**Comment by soninob** [comment]
Closing, no longer relevant.
