### ISSUE TITLE
triggiering job when working with https

### ISSUE THREAD

**Issue by alexmish** [Verigreen/verigreen#117]
hey . 
retriving jobs from jenkins succefuly but no job is triggered when working with https://jenknins

no probelm when triggering on http jenkins 
- VG deplyed with docker

**Comment by edagan** [comment]
Hi,
Might need to import the HTTPS SSL certificate within the docker container.
docker exec into the running container and import the certificate to the Java certificate store.
This script can be used for this:
https://raw.githubusercontent.com/Verigreen/verigreen/master/utils/import-jenkins-ssl-certificate/getCert.sh

After importing the certificate, Jenkins HTTPS calls should work.
Note, however, that the docker VG image need either be changed to include the modified certificate store,  or have the cert store file available via a filesystem mount. 
As is specified in the script, the file is located at: $JAVA_HOME/jre/lib/security/cacerts

Alternatively, the ca certificate store in the docker image could be updated, using update-ca-certificates.

Hope this helps!

**Comment by soninob** [comment]
@edagan thank you. Some more info - @gizmo83 used the script (getCert), and after doing that he was able to retrieve the Job details (a single operation on startup), but wasn't able to trigger it.

**Comment by edagan** [comment]
If the job can be read via HTTPS, then triggering should also be possile.
From within the container - Manually import the certificate, then try to manually trigger the job using CURL.
This call often works. May need to install curl within the image.
`curl -X POST -u user:password  http://HOST:PORT/job/JOBNAME/buildWithParameters?PARAMETER=VALUE`

**Comment by soninob** [comment]
@alexmish is this still relevant? can we close this one?

**Comment by alexmish** [comment]
Sorry for the late response , we postpone the integration ,you can close it
I hope to get back to it and try again soon . Thanks for you help

On Nov 27, 2016 16:21, "Barak Nisim Sonino" <notifications@github.com>
wrote:

@alexmish <https://github.com/alexmish> is this still relevant? can we
close this one?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Verigreen/verigreen/issues/117#issuecomment-263124909>,
or mute the thread
