### ISSUE TITLE
Does verigreen on tomcat support multiple projects?

### ISSUE THREAD

**Issue by rachant** [Verigreen/verigreen#119]
We are looking to verify multiple projects using verigreen. When deployed on tomcat VG_HOME is config/config.properties. How do I add an other project to this setup?

**Comment by rqc** [comment]
From what I understand, verigreen doesn't have multi-repository support. You would need one instance for each repo. 

@soninob @edagan please confirm this.

**Comment by soninob** [comment]
@rachant, if the projects are located on a different repositories then you will need to deploy another instance. 
Not sure if you using our container based solution, but if not, the recommendation deploy is using our Docker container. It is a lot easier to use.

**Comment by soninob** [comment]
@rachant if you think there is a reason to keep that open, please reopen. Closing.
