### ISSUE TITLE
Setting up with beanstalk

### ISSUE THREAD

**Issue by superjd** [Verigreen/verigreen#124]
Not an issue but has anyone setup verigreen with beanstalk?

Thanks

**Comment by rqc** [comment]
Not that I am aware of, @soninob @edagan how about you?

**Comment by superjd** [comment]
Anyone tried using beanstalk and verigreen?, beanstalk does have the ability to set up a modular webhook (http://support.beanstalkapp.com/article/955-modular-webhooks-integration) but not sure if this would work.

Thanks

**Comment by soninob** [comment]
We haven't tried it, feel free to start a PR for it, will love to review it.
let me know if you need any help
