### ISSUE TITLE
Is verigreed still actively developed?

### ISSUE THREAD

**Issue by aleitamar** [Verigreen/verigreen#126]
My team is considering using it.
I don't see any commits for about a year...

**Comment by EricVogl** [comment]
We're also investigating using Verigreen, but just noticed verigreen.io domain registration lapsed.

**Comment by rqc** [comment]
This project has been discontinued (from corporate support).

**Comment by soninob** [comment]
The project is still being supported unofficial (like most open source projects are), feel free to use it, if you have any questions, feel free to submit. I will check it from time to time.
