### ISSUE TITLE
Error: No credentials for preemptive authentication

### ISSUE THREAD

**Issue by aleitamar** [Verigreen/verigreen#129]
Hi @soninob 
i'm getting an error when trying to trigger jenkins jobs:
"No credentials for preemptive authentication"

i saw you had the same issue:
https://stackoverflow.com/questions/25660937/no-credentials-for-preemptive-authentication-port-is-returning-1

How did you manage to solve this?
My jenkins container runs on port 8080

**Comment by aleitamar** [comment]
Turns out this was a docker configuration issue which caused verigreen to fail when connecting to jenkins.

**Comment by soninob** [comment]
good to know! thanks!
