### ISSUE TITLE
Failed item with "Passed by child" parent sets all the children to "Not started"

### ISSUE THREAD

**Issue by borzamircea** [Verigreen/verigreen#74]
An item which has any failed status, with a "Passed by child" parent is not set as "Done". Thus, within the house of cards the item is reset to "Not started" and all of its children are set themselves to "Not started".

The scenario is difficult to replicate in a real flow, because the possibility of a failed item having a PBC parent is highly unlikely.

It can, however, be replicated by starting 5 commits,canceling  commit 1 in Jenkins and setting it to PBC in "Debug mode" of the IDE. Then, commit 2 can be failed, and the above mentioned issue occurs, meaning commits 2,3,4 and 5 are set to "Not started".

**Comment by soninob** [comment]
fixed in PR 75
