### ISSUE TITLE
cacheloader folder creation issue

### ISSUE THREAD

**Issue by edagan** [Verigreen/verigreen#78]
VG 2.5.3 is creating its cacheloader folder under: _/${env.VG_HOME}_
This is the actual name, it does not translate _${env.VG_HOME}_ to _/vg_, even tough it is set (see below).
This is a regression from VG 2.5.2, in which this works OK (just verified).
Please fix.

`root@hostname:/${env.VG_HOME}# echo $VG_HOME`
`/vg`
`root@hostname:/${env.VG_HOME}# ls -l`
`total 4`
`drwxr-xr-x 2 root root 4096 Oct 27 09:45 cacheloader`

**Comment by soninob** [comment]
@edagan - please check the way you mapped  VG_HOME to /vg
the cacheloader is getting created according to the environment variable definition (VG_HOM).

**Comment by soninob** [comment]
A fix in tomcat setenv file is needed:

export VG_HOME="/DATA/VG/verigreen/garda/config"
export CATALINA_OPTS="-Denv.VG_HOME=$VG_HOME"

**Comment by soninob** [comment]
@edagan - can we close this one?

**Comment by edagan** [comment]
Feel free
