### ISSUE TITLE
Commit set to Running after it was set to PBC

### ISSUE THREAD

**Issue by AndreeaDora** [Verigreen/verigreen#79]
A commit is set to Running after it was set to PBC. 
 2 commits: A, B .
                A got trigger failed, B is still running.
                We do a retry for A. A is set to Not started, B is getting passed.
                B is still having A set as his parent so is setting A to PBC. 
                But the same item is handled as not started because we do not do a refresh of the list of items we handle. So from PBC the commit is set to Running.

**Comment by soninob** [comment]
Fixed in release 2.5.5
