### ISSUE TITLE
Merge Failed retry logic

### ISSUE THREAD

**Issue by DVir669** [Verigreen/verigreen#87]
In case of merge failure at the end of the process, the retry should only try to merge the sources again, and not trigger another process. if the verification of the push was already successful, no need to run the same process again

**Comment by soninob** [comment]
@DVir669 - MERGE_FAILED should occur in the beginning of the process before triggering any build.
If 'merge failed' occur after PASS verification - it's indicated on a problem in the Jenkins job.
Even if a permitted user put the local repository out of sync with the protected branch, there is a mechanism that align the branches before actually doing the push.
The only reason I can think of (for now) is that the temp branch is not being verified against the protected branch.

**Comment by soninob** [comment]
@DVir669 - are you agree on closing this one? do you still think it is an issue?

**Comment by DVir669** [comment]
Close it for now - I only had one instance in which it was relevant (no Jenkins job failure - proper GIT issue) - if I'll be able to reproduce I'll make sure to open it again :)
