### ISSUE TITLE
Jenkins API - Check if job is still building before returning the status

### ISSUE THREAD

**Issue by DVir669** [Verigreen/verigreen#91]
When building a job, there are many plugins that are manipulating the status of the build. 
Most common is "trigger\call builds on other projects" -> if the triggered job is blocking the build flow any result from the downstream will result in manipulation of the status. 

VG is looking at the job's API to return the status - when it is set the status is returned before the actual job is finished. 

To fix it the logical way is to make sure that the build is not running anymore by using: 
instead of : builds[number,result]
Use : builds[number,result,building] and check if building == false before returning the status. 
Thanks,
Dvir

**Comment by soninob** [comment]
Been fixed by #93
