### ISSUE TITLE
Add vi to the docker image 

### ISSUE THREAD

**Issue by DVir669** [Verigreen/verigreen#92]
In the next version \ release - can you please add vi to the docker image? 
Some find it more comfortable to work with the logs like that :)

**Comment by rqc** [comment]
If your verigreen container is running in the background you can always use `docker logs <container-name-or-id>` to look at the container output. Let us know if that helps you out.

**Comment by DVir669** [comment]
Thanks, I can also access the docker container and user less or cat to read. 
If I want to Edit though, it is a bit more problematic. 
Either way I used : 
apt-get update
apt-get install vim

It is good enough. just a bother to do every time I deploy the container.

**Comment by rqc** [comment]
@DVir669 could you describe a use case in which you would need to edit a log file? I think logs are more useful to be read / processes versus edited manually.

**Comment by eitansch** [comment]
@DVir669 - we try to minimize the image size (and layers) to a bare minimum and install as little dependencies as possible to maintain a minimal viable set of working software.
If you have a need to extend the image you can always write a wrapper around your pull operation that will add the needed functionality as an additional layer above the base image we supply to you and thus gain any needed functionality without compromising the base image we provide.
You could use an orchestration tool (...) to achieve that goal easily. I can point you to some - [cloudslang](http://cloudslang.io/#/) are awesome!

**Comment by soninob** [comment]
@DVir669 - do I have the green light to close this one?

**Comment by DVir669** [comment]
Please do :) 
Thanks!
