### ISSUE TITLE
After a retry clear the old build URL

### ISSUE THREAD

**Issue by DVir669** [Verigreen/verigreen#95]
When we retry a build, there is a new line that is added to the UI, and the main line gets a (+) to show previous runs on that commit - this is a great behaviour . 
It is confusing the developers that the new line already have a "build url" with the old link - it should be empty pending the run. 
![vg issue](https://cloud.githubusercontent.com/assets/7555985/12377553/7059ca9c-bd2a-11e5-8ea3-2787944ece35.png)

Thanks! 
Dvir

**Comment by soninob** [comment]
@DVir669 - it should be updated after a few seconds that it gets started.
Do you have a PR to solved it? Feel free to submit one :-)

**Comment by DVir669** [comment]
Let's set a meeting so I can get into the code and see how I can contribute :)
