### ISSUE TITLE
Could not resolve collector.address

### ISSUE THREAD

**Issue by pubaayaam** [Verigreen/verigreen#96]
The key value pair is collector.address=http://172.27.59.40:8007/verigreen.
I can access the dashboard from web browser as shown in attachement.
  However, while pushing the git chage, I am facing below exception message. How can I resolve it?
![ems_db git verigreen gui](https://cloud.githubusercontent.com/assets/8557330/12417610/479438b2-becf-11e5-88c8-e7bd78069480.png)

BeanDefinitionStoreException: Invalid bean definition with name 'collectorAddress' defined
in URL [jar:file:/var/atlassian/application-data/stash/bin/git-hooks/verigreen/h
ook/git-hook.jar!/Spring/git-hook-rest-context.xml]: Could not resolve placehold
er 'collector.address' in string value "${collector.address}"

**Comment by soninob** [comment]
@prakashsinhab - did you define the collector address in the hook.properties file?
Please check the installation for the hook as describe here:
https://github.com/Verigreen/verigreen/wiki/Verigreen-Hook-Deployment
section 2.
Let me know for any issue.

**Comment by pubaayaam** [comment]
I feel that, from remote repository, hook.properties file, should also read this key value pair as it is, then, it will work out. I have suggested it within team. Once, she is back from her vacation, I will work out the solution with her coordination.
I wll update the solution trials in a couple of days.
Yes.

**Comment by soninob** [comment]
the hook properties file should belocated on the same machine where the pre-received hook is located (SCM machine). 
if it is define that way, please add 'rest' to the link:
http://172.27.59.40:8007/verigreen/rest

**Comment by soninob** [comment]
@prakashsinhab - any news about this one? did you manage to set the hook and the collector?

**Comment by pubaayaam** [comment]
I updated the URL with /rest action. I am, however, still facing the same issue. I would post the directory structure and file conent of configuration by end of this week.

**Comment by pubaayaam** [comment]
Please find attached all of the specifications from files and directory structures.

![git-hook jar spring file vg_hook folder content to be properties file](https://cloud.githubusercontent.com/assets/8557330/12972531/05eac304-d0cc-11e5-9a50-8072db03debf.png)
[localhost.2016-01-15.log.txt](https://github.com/Verigreen/verigreen/files/126094/localhost.2016-01-15.log.txt)
[config.properties.txt](https://github.com/Verigreen/verigreen/files/126093/config.properties.txt)
![verigreen local](https://cloud.githubusercontent.com/assets/8557330/12972529/05b3a680-d0cc-11e5-8be3-ba5b049e5b9d.png)
![hook properties remote](https://cloud.githubusercontent.com/assets/8557330/12972528/05b103bc-d0cc-11e5-9280-edca7a0dddb6.png)
![remote fliesystem structure](https://cloud.githubusercontent.com/assets/8557330/12972526/05a9ace8-d0cc-11e5-84c3-c60a06bf1afb.png)
![execute sh content](https://cloud.githubusercontent.com/assets/8557330/12972527/05acb4ec-d0cc-11e5-9bf0-d2b22da97af8.png)
![hook folder structure remote](https://cloud.githubusercontent.com/assets/8557330/12972530/05b87c78-d0cc-11e5-8b0c-b1293afd298e.png)

Please suggest all possible missing links in this configuration so that I can take help from our ALM team IS team in updaing remote server configuration along with my local setup of git repo and verigreen setup.

**Comment by borzamircea** [comment]
Hi @prakashsinhab 

Your git.repositoryLocation should contain an ending `.git`, like so:

`git.repositoryLocation=C:\\Users\\borza\\workspace\\playground\\regular_repo\\mircea_test\\.git`

In the case of Linux, you should use `/` instead of `\\`. 

Thanks!

**Comment by soninob** [comment]
Thank you @prakashsinhab for your input.
Please consider the following:
1)  According to your exception in the hook logs, you are still running the hook with java 8.
     make sure to adjust your execute.sh to run with java 7. the last line should be modified to $JAVA_HOME/bin/java -jar (instead of java -jar)  
2) in your config.properties, I would suggest the following:
     put a value to the mail.server filed so you will be able to get the email notification.
     If you didn't modify the war file or change it with tomcat, then your URL should be something like that: http://172.27.59.40:8007/verigreen-collector/rest - but again if you modified the war then no need.
3) hook.properties - all you need in this file is the collector.address field, the rest of the fields are redundant.
4) please consider @borzamircea  comment.

**Comment by soninob** [comment]
Closing, @prakashsinhab - if you didn't manage to solve it, please reopen again.

**Comment by pubaayaam** [comment]
Okay

Thanks @soninob
